name: Node.js CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing my packages
        run: npm install

      - name: Build my App
        run: npm run build

      - run: touch ./dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
